FROM python:3.13-slim-bookworm

ENV PYTHONUNBUFFERED=1
ENV UV_PROJECT_ENVIRONMENT=/.venv

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN pip install uv && \
    groupadd -g 1000 appuser && \
    useradd -u 1000 -g appuser -m -s /bin/bash appuser && \
    mkdir -p $UV_PROJECT_ENVIRONMENT && \
    chown -R appuser:appuser $UV_PROJECT_ENVIRONMENT /app

USER appuser

RUN uv venv && uv sync

EXPOSE 8000
